### ISSUE TITLE
Application notification

### ISSUE THREAD

**Issue by ZeTro-dev** [zelytra/BetterFleet#139]
Change the location of the 'alert' notifications display and move them to the bottom right as shown in the image.

![image](https://github.com/zelytra/BetterFleet/assets/84403666/26b9ff3b-7b1b-4564-8a37-69272a2d0035)

**Comment by zelytra** [comment]
No okay with this, @dadodasyra what do you thinks ?

**Comment by dadodasyra** [comment]
Don't really know why we would need to change that. But it's true that if we think from a consistency level. Notification are at bottom right on windows and at the top for most mobile app..
