### ISSUE TITLE
Patch language bug

### ISSUE THREAD

**Issue by ZeTro-dev** [zelytra/BetterFleet#149]
Related to issue #148 , when you change the language on the preference page, the other languages remain in the previous language.

Demo:

I switch my app to Spanish, so I indeed have "English" etc.
![image](https://github.com/zelytra/BetterFleet/assets/84403666/d442ce7a-c72b-491e-9ffe-18b10a084d30)

I leave the preference page, come back to it, switch back to French, and I still have the other languages translated into Spanish:

![image](https://github.com/zelytra/BetterFleet/assets/84403666/6c087ddd-81c5-479b-8996-4cbad37ecd3e)

**Comment by dadodasyra** [comment]
And maybe the language shouldn't be translated at all

**Comment by ZeTro-dev** [comment]
Yes, it should also stay in the default status, so all languages are translated into English.

**Comment by zelytra** [comment]
it's not related to #148
