### ISSUE TITLE
Display language

### ISSUE THREAD

**Issue by ZeTro-dev** [zelytra/BetterFleet#150]
When a language, for example, "French," is selected, it should be removed from the list of languages to select. Or it should be highlighted to indicate that it is already selected.

**Comment by zelytra** [comment]
I'm not sure about this functionality @dadodasyra what do you think ?

**Comment by dadodasyra** [comment]
> I'm not sure about this functionality @dadodasyra what do you think ?

Don't really have a precise opinion on this. But since it's already selected and the dropdown is not hiding the current selected it make sense to remove it. But we should be able to click on the current selected (which probably already work)

**Comment by zelytra** [comment]
You can click on the same language as selected but it does nothing so... hmmm. maybe just delete the selected i dont know
