### ISSUE TITLE
Launch a forced session

### ISSUE THREAD

**Issue by ZeTro-dev** [zelytra/BetterFleet#151]
When less than half of the players are not ready and the master wants to start the game, a popup window should open to ask for confirmation again, indicating that not all players are ready.

**Comment by zelytra** [comment]
Where is the designe =) ?

**Comment by ZeTro-dev** [comment]
![BetterFleet](https://github.com/zelytra/BetterFleet/assets/84403666/5d7be553-7876-4399-bebd-84d314b7f83e)

**Comment by ZeTro-dev** [comment]
![BetterFleet](https://github.com/zelytra/BetterFleet/assets/84403666/d537ad11-0130-40ac-aeda-731d07883457)
