### ISSUE TITLE
Leave the session button

### ISSUE THREAD

**Issue by ZeTro-dev** [zelytra/BetterFleet#152]
Add a confirmation window to the button for leaving the session, asking for confirmation again if the player really wants to leave the session to avoid "misclicks" or similar issues.

**Comment by zelytra** [comment]
Where is the designe =) ?

**Comment by ZeTro-dev** [comment]
![BetterFleet-1](https://github.com/zelytra/BetterFleet/assets/84403666/8301ca75-0e22-4f6d-98d3-687ffb5dae4a)

**Comment by ZeTro-dev** [comment]
![BetterFleet-1](https://github.com/zelytra/BetterFleet/assets/84403666/b9159a65-6050-46eb-a869-120bf273ee3e)
