### ISSUE TITLE
Sonor countdown for Xbox/PS5 player

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#159]
To avoid the alliance master to countdown in vocal, add a sound to warn player when to click on "rise anchor"

**Comment by zelytra** [comment]
We need a designe for the preferences page, with a check button to enable/disable this feature

**Comment by ZeTro-dev** [comment]
Done
![image](https://github.com/zelytra/BetterFleet/assets/84403666/98f62577-3ed0-4343-babb-084db4e55434)
