### ISSUE TITLE
Better crash handling

### ISSUE THREAD

**Issue by dadodasyra** [zelytra/BetterFleet#186]
We should : 
- Log a lot of stuff in a debug file in program files (from both rust & js)
- Clear logs file from "> 1 week" 
- Suggest to the user to report its crash logs to our backend server on next boot if the app crashed (+ text input for user ?)

**Comment by zelytra** [comment]
Add tauri function to let the frontend build the report and send it to the backend : 
- [ ] getLogs() : return the latest logs (maybe the last hour ones)
- [ ] sendLog() : Let the frontend add log to the log file, to log some frontend event
- [ ] getSystemInfo(): Return the OS sys info of the user

The log need to be formated this way : 
```log
[16:46:35-26-04-2024] [RUST] Server found : 8.8.8.8
[16:46:35-26-04-2024] [FRONTEND] User join a session ABCDEF
``` 
The OS message need to be formated this way:
```log
OS: Windows 11
```

I don't know what you can retrieve from the OS system, i let you add more details if needed
