### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by ZeTroo** [zelytra/BetterFleet#261]
Follow the template provided #200  and redo the profile banner in the parameter page.

**Comment by zelytra** [comment]
Duplicated with #213, you didn't respond and we're not agree with this new design

**Comment by ZeTro-dev** [comment]
Yes, you prefer it for simplicity's sake, except that the preference page must have no "direct" links with the design of the sessions page and therefore with this design. And the green outline on the user banner isn't there by chance, but to highlight this information.

**Comment by zelytra** [comment]
i'm not agree, @dadodasyra say you word. To me it's a no go.

**Comment by dadodasyra** [comment]
> i'm not agree, @dadodasyra say you word. To me it's a no go.

Hello not agree!
Seems not like a big deal for me but the readibility of the red is not that good on the background so the current one is better for accessibility
