### ISSUE TITLE
Login and registration page

### ISSUE THREAD

**Issue by ZeTroo** [zelytra/BetterFleet#262]
Respect the design intended for the application.
![Group 2478](https://github.com/zelytra/BetterFleet/assets/84403666/2c0f7d58-42a0-45ab-beb5-ecb0717fb366)

**Comment by zelytra** [comment]
The design is respected, be more clearer please in your request

**Comment by ZeTro-dev** [comment]
The background has not been done, nor have the elements on the diagonals of the page.

**Comment by zelytra** [comment]
![image](https://github.com/zelytra/BetterFleet/assets/72125876/3512c82e-0752-4986-924f-9a3e01492589)
