### ISSUE TITLE
Error getting IP addresses: Unknow host. (os error 11001)

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#283]
## Summary

A user cannot retrieve the servr info. The game status is ok. It run in admin mode. No special install found. All setup seams to be fine.

## Steps to reproduce

No reproduce for now

## What is the current bug behavior?

Impossible to retrieve the server info

## What is the expected correct behavior?

Should retrieve server info

## Relevant logs and/or screenshots

```shell
Using netstat powershell to get main_menu_port
Asset `vite.svg` not found; fallback to vite.svg.html
Asset `vite.svg` not found; fallback to vite.svg/index.html
Asset `vite.svg` not found; fallback to index.html
[3074, 49255]
Asset `vite.svg` not found; fallback to vite.svg.html
Asset `vite.svg` not found; fallback to vite.svg/index.html
Asset `vite.svg` not found; fallback to index.html
Error getting IP addresses: Hôte inconnu. (os error 11001)
Error getting IP addresses: Hôte inconnu. (os error 11001)
Error getting IP addresses: Hôte inconnu. (os error 11001)
Error getting IP addresses: Hôte inconnu. (os error 11001)
```

**Comment by dadodasyra** [comment]
Need details of network config

**Comment by zelytra** [comment]
For the first user: 
- No VPN
- Classic demestic network without any special config

**Comment by dadodasyra** [comment]
> For the first user:
> 
> * No VPN
> * Classic domestic network without any special config

![image](https://github.com/zelytra/BetterFleet/assets/44753923/ecae8fe9-b900-4c07-8236-28a60f6ac6ae)
I need this UI in control panel

**Comment by dadodasyra** [comment]
The error come from https://github.com/zelytra/BetterFleet/blob/43412f352d7922c63211e629092f73b3ca719e08/webapp/src-tauri/src/fetch_informations.rs#L78-L85

Maybe hostname contains a domain name (even if it shouldn't) so it crashes. This is probably related to a strange network configuration as said earlier

**Comment by zelytra** [comment]
A screenshot of the network from a user who as the poblem:
![image](https://github.com/zelytra/BetterFleet/assets/72125876/36c6b6c3-4d72-4fbd-92c5-9f69251bed65)
