### ISSUE TITLE
Shortcut to be ready

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#287]
## Description of needs

Add an option of preferences page, to let the user setup a shortcut that permit him to be ready on the session without opening the app

## Acceptance criteria (done when...)
- [ ] Preference input to setup the shortcut
- [ ] The shortcut can be executed outside of the app without focus
- [ ] The shortcut toggle the ready status
- [ ] Add a sound to let theuser know without seeing the app if he is ready or not when pressing the shortcut

**Comment by zelytra** [comment]
@dadodasyra what do you think ?

**Comment by dadodasyra** [comment]
I'm afraid people dont understand that it triggers outside of the app and will put a single key on it. 
Should we cancel the behavior of the key too ?

**Comment by zelytra** [comment]
We can add a small description in the preference page when setup, like the auto game launch disable/enable.
Btw we're not supposing to disable the behavior of the key, like discord shortcut it can `ctrl + X` by ex. So i don't understand the purpose of concel the behaviour of the key.

To make sure the user is not setting a bais key. Maybe forcing it to be `CTRL` + the key the user want
